name: Terraform CI/CD Pipeline

on:
  push:
    branches: [ main, dev, feat/devops-sprint3-infrastructure ]
  pull_request:
    branches: [ main, dev ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Format Check
        working-directory: terraform/environments/dev
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: terraform/environments/dev
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform/environments/dev
        run: terraform validate